name: Publish to PyPI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    name: Build & Publish to PyPI
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: pypi
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python (latest)
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install project deps (optional extras)
        run: uv sync --all-groups

      - name: Build distributions
        run: uv build

      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish --check-url https://pypi.org/simple
